import type { Job } from "@/lib/actions/shared.types.d.ts";
// Mock data for jobs
export const mockJobs: Job[] = [
  {
    job_id: "1",
    job_title: "Frontend Developer",
    job_apply_link: "https://example.com/apply/1",
    employer_name: "TechCorp",
    job_country: "us",
    job_city: "San Francisco",
    job_employment_type: "Full-time",
    job_min_salary: 80000,
    job_max_salary: 120000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Develop responsive and interactive web applications using React, TypeScript, and modern CSS frameworks. Collaborate with UX designers to implement pixel-perfect interfaces and optimize for performance across devices.",
  },
  {
    job_id: "2",
    job_title: "Backend Engineer",
    job_apply_link: "https://example.com/apply/2",
    employer_name: "DataSystems",
    job_country: "gb",
    job_city: "London",
    job_employment_type: "Full-time",
    job_min_salary: 70000,
    job_max_salary: 100000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Design and implement scalable backend systems and RESTful APIs using Node.js and Express. Work with databases like MongoDB and PostgreSQL, and integrate with cloud services on AWS or Azure.",
  },
  {
    job_id: "3",
    job_title: "UX Designer",
    job_apply_link: "https://example.com/apply/3",
    employer_name: "DesignHub",
    job_country: "ca",
    job_city: "Toronto",
    job_employment_type: "Contract",
    job_min_salary: 75000,
    job_max_salary: 110000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Create intuitive user experiences for web and mobile applications. Conduct user research, develop wireframes and prototypes, and collaborate with developers to ensure smooth implementation of designs.",
  },
  {
    job_id: "4",
    job_title: "Data Scientist",
    job_apply_link: "https://example.com/apply/4",
    employer_name: "AnalyticsPro",
    job_country: "de",
    job_city: "Berlin",
    job_employment_type: "Full-time",
    job_min_salary: 85000,
    job_max_salary: 130000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Analyze complex datasets using advanced statistical methods and machine learning algorithms. Develop predictive models, create data visualizations, and present insights to stakeholders. Proficiency in Python, R, and SQL required.",
  },
  {
    job_id: "5",
    job_title: "DevOps Engineer",
    job_apply_link: "https://example.com/apply/5",
    employer_name: "CloudTech",
    job_country: "au",
    job_city: "Sydney",
    job_employment_type: "Full-time",
    job_min_salary: 90000,
    job_max_salary: 140000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Design, implement, and maintain CI/CD pipelines. Manage cloud infrastructure on AWS, Azure, or GCP. Automate deployment processes, monitor system performance, and ensure high availability and scalability of applications.",
  },
  {
    job_id: "6",
    job_title: "Mobile App Developer",
    job_apply_link: "https://example.com/apply/6",
    employer_name: "AppWizards",
    job_country: "in",
    job_city: "Bangalore",
    job_employment_type: "Full-time",
    job_min_salary: 50000,
    job_max_salary: 80000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Develop native and cross-platform mobile applications for iOS and Android using Swift, Kotlin, and React Native. Implement responsive UI designs, integrate with backend APIs, and optimize app performance and user experience.",
  },
  {
    job_id: "7",
    job_title: "Product Manager",
    job_apply_link: "https://example.com/apply/7",
    employer_name: "InnovateCo",
    job_country: "fr",
    job_city: "Paris",
    job_employment_type: "Full-time",
    job_min_salary: 95000,
    job_max_salary: 150000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Lead the development and execution of product strategies. Gather and analyze market data, define product roadmaps, and work closely with engineering, design, and marketing teams to deliver innovative solutions that meet user needs.",
  },
  {
    job_id: "8",
    job_title: "Cybersecurity Analyst",
    job_apply_link: "https://example.com/apply/8",
    employer_name: "SecureNet",
    job_country: "sg",
    job_city: "Singapore",
    job_employment_type: "Full-time",
    job_min_salary: 80000,
    job_max_salary: 120000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Implement and maintain security measures to protect organizational data and systems. Conduct security assessments, respond to incidents, and develop security policies. Experience with SIEM tools, penetration testing, and compliance frameworks required.",
  },
  {
    job_id: "9",
    job_title: "AI Research Scientist",
    job_apply_link: "https://example.com/apply/9",
    employer_name: "AIFuture",
    job_country: "jp",
    job_city: "Tokyo",
    job_employment_type: "Full-time",
    job_min_salary: 100000,
    job_max_salary: 160000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Conduct cutting-edge research in areas such as natural language processing, computer vision, and reinforcement learning. Develop and implement novel AI algorithms, publish research papers, and collaborate with cross-functional teams to apply AI solutions to real-world problems.",
  },
  {
    job_id: "10",
    job_title: "Technical Writer",
    job_apply_link: "https://example.com/apply/10",
    employer_name: "DocuTech",
    job_country: "nl",
    job_city: "Amsterdam",
    job_employment_type: "Part-time",
    job_min_salary: 45000,
    job_max_salary: 70000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Create clear, concise, and user-friendly documentation for software products and APIs. Collaborate with developers and product managers to understand complex technical concepts and translate them into easily understandable content for various audiences.",
  },
  {
    job_id: "11",
    job_title: "QA Engineer",
    job_apply_link: "https://example.com/apply/11",
    employer_name: "BugBusters",
    job_country: "se",
    job_city: "Stockholm",
    job_employment_type: "Full-time",
    job_min_salary: 70000,
    job_max_salary: 100000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Design and implement comprehensive test strategies for software applications. Develop and maintain automated test suites, perform manual testing, and work closely with developers to ensure high-quality software releases. Experience with Selenium, Jest, and CI/CD tools preferred.",
  },
  {
    job_id: "12",
    job_title: "Blockchain Developer",
    job_apply_link: "https://example.com/apply/12",
    employer_name: "CryptoInnovate",
    job_country: "ch",
    job_city: "Zurich",
    job_employment_type: "Contract",
    job_min_salary: 110000,
    job_max_salary: 180000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Design and develop decentralized applications (dApps) and smart contracts on blockchain platforms such as Ethereum, Solana, or Polkadot. Implement cryptographic protocols, optimize gas usage, and ensure the security and efficiency of blockchain solutions.",
  },
  {
    job_id: "13",
    job_title: "UI/UX Researcher",
    job_apply_link: "https://example.com/apply/13",
    employer_name: "UserFirst",
    job_country: "br",
    job_city: "São Paulo",
    job_employment_type: "Full-time",
    job_min_salary: 60000,
    job_max_salary: 90000,
    employer_logo: "/assets/icons/account.svg",
    job_description:
      "Plan and conduct user research studies to inform product design decisions. Utilize various research methodologies such as usability testing, surveys, and interviews. Analyze and synthesize research data to provide actionable insights to product and design teams.",
  },
];
